version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gh-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /worker
    schedule:
      interval: weekly
    groups:
      worker-deps:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
    groups:
      api-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-deps:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
    groups:
      infra-images:
        patterns: ["*"]
