"""Initial schema — users, global_books, user_library, highlights, collections.

Revision ID: 0001
Revises:
Create Date: 2026-05-13

Matches ``ARCHITECTURE.md`` §4. Hand-written rather than autogenerated so the
repo is bootstrappable without a live Postgres.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "global_books",
        sa.Column("book_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("isbn", sa.String(length=20), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("minhash_signature", sa.LargeBinary(), nullable=False),
        sa.Column("text_pointer", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "user_library",
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("book_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_user_library_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["global_books.book_id"],
            name="fk_user_library_book_id",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("user_id", "book_id", name="uq_user_library_user_book"),
    )
    op.create_index(
        "ix_user_library_user_id",
        "user_library",
        ["user_id"],
    )

    op.create_table(
        "highlights",
        sa.Column("highlight_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("book_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("vector_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_highlights_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["global_books.book_id"],
            name="fk_highlights_book_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_highlights_user_book",
        "highlights",
        ["user_id", "book_id"],
    )

    op.create_table(
        "collections",
        sa.Column("collection_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_collections_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_collections_user_id",
        "collections",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_collections_user_id", table_name="collections")
    op.drop_table("collections")

    op.drop_index("ix_highlights_user_book", table_name="highlights")
    op.drop_table("highlights")

    op.drop_index("ix_user_library_user_id", table_name="user_library")
    op.drop_table("user_library")

    op.drop_table("global_books")
    op.drop_table("users")
